name: CI Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry, deps and pre-commit
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
        poetry run pre-commit install
    - name: Run pre-commit hooks
      run: |
        poetry run pre-commit run --all-files
